version: '3'
  services:
    app1:
      build: .
        environment:
          - APP_NAME:APP1
        ports:
         - "5001:5000"
    app2:
      build: .
        environment:
          - APP_NAME:APP2
        ports:
         - "5002:5000"
    app3:
      build: .
        environment:
          - APP_NAME:APP3
        ports:
         - "5003:5000"
   
